/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuncionalidadesRouteImport } from './routes/funcionalidades'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as AccederRouteImport } from './routes/acceder'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuperRouteImport } from './routes/_authenticated/super'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSuperIndexRouteImport } from './routes/_authenticated/super.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSuperUsuariosRouteImport } from './routes/_authenticated/super.usuarios'
import { Route as AuthenticatedSuperTenantsRouteImport } from './routes/_authenticated/super.tenants'
import { Route as AuthenticatedSuperPlanesRouteImport } from './routes/_authenticated/super.planes'
import { Route as AuthenticatedSuperHealthRouteImport } from './routes/_authenticated/super.health'
import { Route as AuthenticatedSuperFacturacionRouteImport } from './routes/_authenticated/super.facturacion'
import { Route as AuthenticatedSuperEventosRouteImport } from './routes/_authenticated/super.eventos'
import { Route as AuthenticatedSuperConfiguracionRouteImport } from './routes/_authenticated/super.configuracion'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminTarifasRouteImport } from './routes/_authenticated/admin.tarifas'
import { Route as AuthenticatedAdminSuministrosRouteImport } from './routes/_authenticated/admin.suministros'
import { Route as AuthenticatedAdminSociosRouteImport } from './routes/_authenticated/admin.socios'
import { Route as AuthenticatedAdminReclamosRouteImport } from './routes/_authenticated/admin.reclamos'
import { Route as AuthenticatedAdminFacturacionSuscripcionRouteImport } from './routes/_authenticated/admin.facturacion-suscripcion'
import { Route as AuthenticatedAdminFacturacionRouteImport } from './routes/_authenticated/admin.facturacion'
import { Route as AuthenticatedAdminConfiguracionRouteImport } from './routes/_authenticated/admin.configuracion'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as ApiPublicBillingWebhookProviderRouteImport } from './routes/api/public/billing-webhook.$provider'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionalidadesRoute = FuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const AccederRoute = AccederRouteImport.update({
  id: '/acceder',
  path: '/acceder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperRoute = AuthenticatedSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperIndexRoute = AuthenticatedSuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSuperRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSuperUsuariosRoute =
  AuthenticatedSuperUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedSuperTenantsRoute =
  AuthenticatedSuperTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedSuperPlanesRoute =
  AuthenticatedSuperPlanesRouteImport.update({
    id: '/planes',
    path: '/planes',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedSuperHealthRoute =
  AuthenticatedSuperHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedSuperFacturacionRoute =
  AuthenticatedSuperFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedSuperEventosRoute =
  AuthenticatedSuperEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedSuperConfiguracionRoute =
  AuthenticatedSuperConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTarifasRoute =
  AuthenticatedAdminTarifasRouteImport.update({
    id: '/tarifas',
    path: '/tarifas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuministrosRoute =
  AuthenticatedAdminSuministrosRouteImport.update({
    id: '/suministros',
    path: '/suministros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSociosRoute =
  AuthenticatedAdminSociosRouteImport.update({
    id: '/socios',
    path: '/socios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReclamosRoute =
  AuthenticatedAdminReclamosRouteImport.update({
    id: '/reclamos',
    path: '/reclamos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFacturacionSuscripcionRoute =
  AuthenticatedAdminFacturacionSuscripcionRouteImport.update({
    id: '/facturacion-suscripcion',
    path: '/facturacion-suscripcion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFacturacionRoute =
  AuthenticatedAdminFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracionRoute =
  AuthenticatedAdminConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicBillingWebhookProviderRoute =
  ApiPublicBillingWebhookProviderRouteImport.update({
    id: '/api/public/billing-webhook/$provider',
    path: '/api/public/billing-webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceder': typeof AccederRoute
  '/casos': typeof CasosRoute
  '/contacto': typeof ContactoRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/login': typeof LoginRoute
  '/precios': typeof PreciosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/super': typeof AuthenticatedSuperRouteWithChildren
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/facturacion': typeof AuthenticatedAdminFacturacionRoute
  '/admin/facturacion-suscripcion': typeof AuthenticatedAdminFacturacionSuscripcionRoute
  '/admin/reclamos': typeof AuthenticatedAdminReclamosRoute
  '/admin/socios': typeof AuthenticatedAdminSociosRoute
  '/admin/suministros': typeof AuthenticatedAdminSuministrosRoute
  '/admin/tarifas': typeof AuthenticatedAdminTarifasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/super/configuracion': typeof AuthenticatedSuperConfiguracionRoute
  '/super/eventos': typeof AuthenticatedSuperEventosRoute
  '/super/facturacion': typeof AuthenticatedSuperFacturacionRoute
  '/super/health': typeof AuthenticatedSuperHealthRoute
  '/super/planes': typeof AuthenticatedSuperPlanesRoute
  '/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/super/usuarios': typeof AuthenticatedSuperUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/super/': typeof AuthenticatedSuperIndexRoute
  '/api/public/billing-webhook/$provider': typeof ApiPublicBillingWebhookProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceder': typeof AccederRoute
  '/casos': typeof CasosRoute
  '/contacto': typeof ContactoRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/login': typeof LoginRoute
  '/precios': typeof PreciosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cliente': typeof AuthenticatedClienteRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/facturacion': typeof AuthenticatedAdminFacturacionRoute
  '/admin/facturacion-suscripcion': typeof AuthenticatedAdminFacturacionSuscripcionRoute
  '/admin/reclamos': typeof AuthenticatedAdminReclamosRoute
  '/admin/socios': typeof AuthenticatedAdminSociosRoute
  '/admin/suministros': typeof AuthenticatedAdminSuministrosRoute
  '/admin/tarifas': typeof AuthenticatedAdminTarifasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/super/configuracion': typeof AuthenticatedSuperConfiguracionRoute
  '/super/eventos': typeof AuthenticatedSuperEventosRoute
  '/super/facturacion': typeof AuthenticatedSuperFacturacionRoute
  '/super/health': typeof AuthenticatedSuperHealthRoute
  '/super/planes': typeof AuthenticatedSuperPlanesRoute
  '/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/super/usuarios': typeof AuthenticatedSuperUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/super': typeof AuthenticatedSuperIndexRoute
  '/api/public/billing-webhook/$provider': typeof ApiPublicBillingWebhookProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/acceder': typeof AccederRoute
  '/casos': typeof CasosRoute
  '/contacto': typeof ContactoRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/login': typeof LoginRoute
  '/precios': typeof PreciosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/cliente': typeof AuthenticatedClienteRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/super': typeof AuthenticatedSuperRouteWithChildren
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/_authenticated/admin/facturacion': typeof AuthenticatedAdminFacturacionRoute
  '/_authenticated/admin/facturacion-suscripcion': typeof AuthenticatedAdminFacturacionSuscripcionRoute
  '/_authenticated/admin/reclamos': typeof AuthenticatedAdminReclamosRoute
  '/_authenticated/admin/socios': typeof AuthenticatedAdminSociosRoute
  '/_authenticated/admin/suministros': typeof AuthenticatedAdminSuministrosRoute
  '/_authenticated/admin/tarifas': typeof AuthenticatedAdminTarifasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/super/configuracion': typeof AuthenticatedSuperConfiguracionRoute
  '/_authenticated/super/eventos': typeof AuthenticatedSuperEventosRoute
  '/_authenticated/super/facturacion': typeof AuthenticatedSuperFacturacionRoute
  '/_authenticated/super/health': typeof AuthenticatedSuperHealthRoute
  '/_authenticated/super/planes': typeof AuthenticatedSuperPlanesRoute
  '/_authenticated/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/_authenticated/super/usuarios': typeof AuthenticatedSuperUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/super/': typeof AuthenticatedSuperIndexRoute
  '/api/public/billing-webhook/$provider': typeof ApiPublicBillingWebhookProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceder'
    | '/casos'
    | '/contacto'
    | '/funcionalidades'
    | '/login'
    | '/precios'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/cliente'
    | '/onboarding'
    | '/super'
    | '/admin/auditoria'
    | '/admin/configuracion'
    | '/admin/facturacion'
    | '/admin/facturacion-suscripcion'
    | '/admin/reclamos'
    | '/admin/socios'
    | '/admin/suministros'
    | '/admin/tarifas'
    | '/admin/usuarios'
    | '/super/configuracion'
    | '/super/eventos'
    | '/super/facturacion'
    | '/super/health'
    | '/super/planes'
    | '/super/tenants'
    | '/super/usuarios'
    | '/admin/'
    | '/super/'
    | '/api/public/billing-webhook/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceder'
    | '/casos'
    | '/contacto'
    | '/funcionalidades'
    | '/login'
    | '/precios'
    | '/register'
    | '/reset-password'
    | '/cliente'
    | '/onboarding'
    | '/admin/auditoria'
    | '/admin/configuracion'
    | '/admin/facturacion'
    | '/admin/facturacion-suscripcion'
    | '/admin/reclamos'
    | '/admin/socios'
    | '/admin/suministros'
    | '/admin/tarifas'
    | '/admin/usuarios'
    | '/super/configuracion'
    | '/super/eventos'
    | '/super/facturacion'
    | '/super/health'
    | '/super/planes'
    | '/super/tenants'
    | '/super/usuarios'
    | '/admin'
    | '/super'
    | '/api/public/billing-webhook/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acceder'
    | '/casos'
    | '/contacto'
    | '/funcionalidades'
    | '/login'
    | '/precios'
    | '/register'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/cliente'
    | '/_authenticated/onboarding'
    | '/_authenticated/super'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/configuracion'
    | '/_authenticated/admin/facturacion'
    | '/_authenticated/admin/facturacion-suscripcion'
    | '/_authenticated/admin/reclamos'
    | '/_authenticated/admin/socios'
    | '/_authenticated/admin/suministros'
    | '/_authenticated/admin/tarifas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/super/configuracion'
    | '/_authenticated/super/eventos'
    | '/_authenticated/super/facturacion'
    | '/_authenticated/super/health'
    | '/_authenticated/super/planes'
    | '/_authenticated/super/tenants'
    | '/_authenticated/super/usuarios'
    | '/_authenticated/admin/'
    | '/_authenticated/super/'
    | '/api/public/billing-webhook/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccederRoute: typeof AccederRoute
  CasosRoute: typeof CasosRoute
  ContactoRoute: typeof ContactoRoute
  FuncionalidadesRoute: typeof FuncionalidadesRoute
  LoginRoute: typeof LoginRoute
  PreciosRoute: typeof PreciosRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicBillingWebhookProviderRoute: typeof ApiPublicBillingWebhookProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades': {
      id: '/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/funcionalidades'
      preLoaderRoute: typeof FuncionalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceder': {
      id: '/acceder'
      path: '/acceder'
      fullPath: '/acceder'
      preLoaderRoute: typeof AccederRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super': {
      id: '/_authenticated/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof AuthenticatedSuperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super/': {
      id: '/_authenticated/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof AuthenticatedSuperIndexRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/super/usuarios': {
      id: '/_authenticated/super/usuarios'
      path: '/usuarios'
      fullPath: '/super/usuarios'
      preLoaderRoute: typeof AuthenticatedSuperUsuariosRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/tenants': {
      id: '/_authenticated/super/tenants'
      path: '/tenants'
      fullPath: '/super/tenants'
      preLoaderRoute: typeof AuthenticatedSuperTenantsRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/planes': {
      id: '/_authenticated/super/planes'
      path: '/planes'
      fullPath: '/super/planes'
      preLoaderRoute: typeof AuthenticatedSuperPlanesRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/health': {
      id: '/_authenticated/super/health'
      path: '/health'
      fullPath: '/super/health'
      preLoaderRoute: typeof AuthenticatedSuperHealthRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/facturacion': {
      id: '/_authenticated/super/facturacion'
      path: '/facturacion'
      fullPath: '/super/facturacion'
      preLoaderRoute: typeof AuthenticatedSuperFacturacionRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/eventos': {
      id: '/_authenticated/super/eventos'
      path: '/eventos'
      fullPath: '/super/eventos'
      preLoaderRoute: typeof AuthenticatedSuperEventosRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/configuracion': {
      id: '/_authenticated/super/configuracion'
      path: '/configuracion'
      fullPath: '/super/configuracion'
      preLoaderRoute: typeof AuthenticatedSuperConfiguracionRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tarifas': {
      id: '/_authenticated/admin/tarifas'
      path: '/tarifas'
      fullPath: '/admin/tarifas'
      preLoaderRoute: typeof AuthenticatedAdminTarifasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suministros': {
      id: '/_authenticated/admin/suministros'
      path: '/suministros'
      fullPath: '/admin/suministros'
      preLoaderRoute: typeof AuthenticatedAdminSuministrosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/socios': {
      id: '/_authenticated/admin/socios'
      path: '/socios'
      fullPath: '/admin/socios'
      preLoaderRoute: typeof AuthenticatedAdminSociosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reclamos': {
      id: '/_authenticated/admin/reclamos'
      path: '/reclamos'
      fullPath: '/admin/reclamos'
      preLoaderRoute: typeof AuthenticatedAdminReclamosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/facturacion-suscripcion': {
      id: '/_authenticated/admin/facturacion-suscripcion'
      path: '/facturacion-suscripcion'
      fullPath: '/admin/facturacion-suscripcion'
      preLoaderRoute: typeof AuthenticatedAdminFacturacionSuscripcionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/facturacion': {
      id: '/_authenticated/admin/facturacion'
      path: '/facturacion'
      fullPath: '/admin/facturacion'
      preLoaderRoute: typeof AuthenticatedAdminFacturacionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracion': {
      id: '/_authenticated/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/billing-webhook/$provider': {
      id: '/api/public/billing-webhook/$provider'
      path: '/api/public/billing-webhook/$provider'
      fullPath: '/api/public/billing-webhook/$provider'
      preLoaderRoute: typeof ApiPublicBillingWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminConfiguracionRoute: typeof AuthenticatedAdminConfiguracionRoute
  AuthenticatedAdminFacturacionRoute: typeof AuthenticatedAdminFacturacionRoute
  AuthenticatedAdminFacturacionSuscripcionRoute: typeof AuthenticatedAdminFacturacionSuscripcionRoute
  AuthenticatedAdminReclamosRoute: typeof AuthenticatedAdminReclamosRoute
  AuthenticatedAdminSociosRoute: typeof AuthenticatedAdminSociosRoute
  AuthenticatedAdminSuministrosRoute: typeof AuthenticatedAdminSuministrosRoute
  AuthenticatedAdminTarifasRoute: typeof AuthenticatedAdminTarifasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminConfiguracionRoute: AuthenticatedAdminConfiguracionRoute,
  AuthenticatedAdminFacturacionRoute: AuthenticatedAdminFacturacionRoute,
  AuthenticatedAdminFacturacionSuscripcionRoute:
    AuthenticatedAdminFacturacionSuscripcionRoute,
  AuthenticatedAdminReclamosRoute: AuthenticatedAdminReclamosRoute,
  AuthenticatedAdminSociosRoute: AuthenticatedAdminSociosRoute,
  AuthenticatedAdminSuministrosRoute: AuthenticatedAdminSuministrosRoute,
  AuthenticatedAdminTarifasRoute: AuthenticatedAdminTarifasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSuperRouteChildren {
  AuthenticatedSuperConfiguracionRoute: typeof AuthenticatedSuperConfiguracionRoute
  AuthenticatedSuperEventosRoute: typeof AuthenticatedSuperEventosRoute
  AuthenticatedSuperFacturacionRoute: typeof AuthenticatedSuperFacturacionRoute
  AuthenticatedSuperHealthRoute: typeof AuthenticatedSuperHealthRoute
  AuthenticatedSuperPlanesRoute: typeof AuthenticatedSuperPlanesRoute
  AuthenticatedSuperTenantsRoute: typeof AuthenticatedSuperTenantsRoute
  AuthenticatedSuperUsuariosRoute: typeof AuthenticatedSuperUsuariosRoute
  AuthenticatedSuperIndexRoute: typeof AuthenticatedSuperIndexRoute
}

const AuthenticatedSuperRouteChildren: AuthenticatedSuperRouteChildren = {
  AuthenticatedSuperConfiguracionRoute: AuthenticatedSuperConfiguracionRoute,
  AuthenticatedSuperEventosRoute: AuthenticatedSuperEventosRoute,
  AuthenticatedSuperFacturacionRoute: AuthenticatedSuperFacturacionRoute,
  AuthenticatedSuperHealthRoute: AuthenticatedSuperHealthRoute,
  AuthenticatedSuperPlanesRoute: AuthenticatedSuperPlanesRoute,
  AuthenticatedSuperTenantsRoute: AuthenticatedSuperTenantsRoute,
  AuthenticatedSuperUsuariosRoute: AuthenticatedSuperUsuariosRoute,
  AuthenticatedSuperIndexRoute: AuthenticatedSuperIndexRoute,
}

const AuthenticatedSuperRouteWithChildren =
  AuthenticatedSuperRoute._addFileChildren(AuthenticatedSuperRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSuperRoute: typeof AuthenticatedSuperRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClienteRoute: AuthenticatedClienteRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSuperRoute: AuthenticatedSuperRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccederRoute: AccederRoute,
  CasosRoute: CasosRoute,
  ContactoRoute: ContactoRoute,
  FuncionalidadesRoute: FuncionalidadesRoute,
  LoginRoute: LoginRoute,
  PreciosRoute: PreciosRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicBillingWebhookProviderRoute: ApiPublicBillingWebhookProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
